/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andfixjni_demo_DxManager */

#ifndef _Included_com_andfixjni_demo_DxManager
#define _Included_com_andfixjni_demo_DxManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andfixjni_demo_DxManager
 * Method:    replaceMethod
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_com_andfixjni_demo_DxManager_replaceMethod
  (JNIEnv *, jobject, jobject, jobject);

JNIEXPORT jstring JNICALL Java_com_andfixjni_demo_DxManager_stringFromJNI
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
